version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose up -d
  deploy:
    steps: 
      - add_ssh_keys:
          fingerprints:
            - 3c:cd:08:8c:62:94:91:ec:4d:a9:a6:72:8d:dd:31:8f
      - run: ssh  StrictHostKeyChecking=no $VULTR_USER@$VULTR_HOST 
      - run: ls -la
workflow:
  build-and-deploy:
    job: 
      - build
      - deploy: 
        requires: 
          - build