version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: strapi/strapi
    steps:
      - checkout
      - run: npm install
  deploy:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - $VULTR_FINGERPRINT
      - run: ssh-keyscan $@$VULTR_HOST >> ~/.ssh/known_hosts
      - run:
          name: VultrDeploy Over SSH
          command: |
            ssh  StrictHostKeyChecking=no $VULTR_USER@$VULTR_HOST docker-compose up

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
