version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  install-and-up:
    docker:
      - image: strapi/strapi
    steps:
      - checkout
      - run: npm install
  build-and-test:
    executor:
      name: node/default
    steps:
      - setup_remote_docker
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  build-and-deploy:
    docker:
      - image: strapi/strapi
    steps:
      - checkout
      - run: npm install

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - aws-ecr/build-and-push-image:
          context: test
          repo: strapi
  build-and-deploy:
    jobs:
      - build-and-deploy
